### ISSUE TITLE
Sound.addMarker causes Sound.volume to only work after Sound.play

### ISSUE THREAD

**Issue by movrajr** [qiciengine/qiciengine-core#2]
Sound.volume is not applied before Sound.play() if Sound.addMarker was called before.

When running the original AudioSprite.js in the AudioSprite demo, the resulting sound object will be 1 regardless of sound.volume:

``` js
AudioSprite.prototype.onClick = function() {
    var sound = this.game.add.sound();
    sound.audio = this.audio;
    sound.addMarker(this.markerStart, this.markerDuration);
    sound.destroyWhenStop = true;
    sound.volume = 0.9;
    sound.play();
};
```

After moving sound.volume behind sound.play(), the resulting sound object will have the expected volume.

``` js
AudioSprite.prototype.onClick = function() {
    var sound = this.game.add.sound();
    sound.audio = this.audio;    
    sound.addMarker(this.markerStart, this.markerDuration);    
    sound.destroyWhenStop = true;        
    sound.play();
    sound.volume = 0.3;    
};
```

**Comment by huhudage** [comment]
We'll fix this issue in the next version, thanks!

After that, you could pass the volume value to the addMarker method before playing. 

For example: 
`sound.addMarker(this.markerStart, this.markerDuration, 0.9);`

**Comment by movrajr** [comment]
Thanks for fixing. 

I'm really impressed by QICI Engine so far. :)
