### ISSUE TITLE
New project with manually typed path failed to open in 1.1.0

### ISSUE THREAD

**Issue by movrajr** [qiciengine/qiciengine-core#3]
After creating a new project by manually typing in a folder name, an error is displayed: "Open project failed". More details are displayed in the console.

No problem opening the new project manually by the way.

This problem occurs in 1.1.0 but not in 1.0.9.

[Example video](https://gfycat.com/SeparateDeepGoldfish)

**Comment by huhudage** [comment]
Fixed already, thanks~
